### ISSUE TITLE
使用onnx导出生成的extract_speaker_embedding时报错

### ISSUE THREAD

**Issue by jiayuan666** [modelscope/3D-Speaker#158]
我使用speakerlab/bin/export_speaker_embedding_onnx.py训练完的模型导出成onnx，
然后使用extract_speaker_embedding时出现下面的报错：
```
In init_mel_bins: num_fft_bins = 256 num_bins = 80 nyquist = 8000 low_frequency = 20 high_frequency = 8000
frame_length: 400 frame_shift: 160 fft_n: 512 num_frames: 299 mel_bins: 80 fbank_num_bins 80 epsilon: 1.19209e-07
terminate called after throwing an instance of 'Ort::Exception'
  what():  Got invalid dimensions for input: feature for the following indices
 index: 2 Got: 80 Expected: 512
 Please fix either the inputs or the model.
Aborted (core dumped)
```
看起来是模型配置或者输入文件的相关错误，训练和推理使用的wav文件同一批数据源
以下是我的模型配置：
```
aug_prob: 0.8
augmentations:
  args:
    aug_prob: <aug_prob>
    noise_file: <noise>
    reverb_file: <reverb>
  obj: speakerlab.process.processor_para.SpkVeriAug
batch_size: 16
checkpointer:
  args:
    checkpoints_dir: <exp_dir>/models
    recoverables:
      classifier: <classifier>
      embedding_model: <embedding_model>
      epoch_counter: <epoch_counter>
      label_encoder: <label_encoder>
  obj: speakerlab.utils.checkpoint.Checkpointer
classifier:
  args:
    input_dim: <embedding_size>
    out_neurons: <num_classes>
  obj: speakerlab.models.campplus.classifier.LinearClassifier
data: /home/zjy/project/3D-Speaker/egs/3dspeaker/language-identification/data/mtscv2.1/train/train.csv
dataloader:
  args:
    batch_size: <batch_size>
    dataset: <dataset>
    drop_last: true
    num_workers: <num_workers>
    pin_memory: true
  obj: torch.utils.data.DataLoader
dataset:
  args:
    data_file: <data>
    preprocessor: <preprocessor>
  obj: speakerlab.dataset.dataset.WavSVDataset
embedding_model:
  args:
    embedding_size: <embedding_size>
    feat_dim: <feat_dim>
    m_channels: <m_channels>
  obj: speakerlab.models.eres2net.ERes2Net.ERes2Net
embedding_size: 192
epoch_counter:
  args:
    limit: <num_epoch>
  obj: speakerlab.utils.epoch.EpochCounter
exp_dir: /home/zjy/project/3D-Speaker/egs/3dspeaker/language-identification/exp/eres2net_para
fbank_dim: 80
feat_dim: 512
feature_extractor:
  args:
    mean_nor: true
    n_mels: <fbank_dim>
    sample_rate: <sample_rate>
  obj: speakerlab.process.processor_para.FBank
fix_epoch: 6
label_encoder:
  args:
    data_file: <data>
  obj: speakerlab.process.processor_para.SpkLabelEncoder
log_batch_freq: 500
loss:
  args: {}
  obj: speakerlab.loss.margin_loss.EntropyLoss
lr: 0.001
lr_scheduler:
  args:
    fix_epoch: <fix_epoch>
    max_lr: <lr>
    min_lr: <min_lr>
    optimizer: <optimizer>
    step_per_epoch: null
    warmup_epoch: <warmup_epoch>
  obj: speakerlab.process.scheduler.WarmupCosineScheduler
m_channels: 32
margin_scheduler:
  args:
    criterion: <loss>
    final_margin: 0.0
    fix_epoch: 0
    increase_start_epoch: 0
    initial_margin: 0.0
    step_per_epoch: null
  obj: speakerlab.process.scheduler.MarginScheduler
min_lr: 0.0001
noise: /home/zjy/project/3D-Speaker/egs/3dspeaker/language-identification/data/musan/wav.scp
num_classes: null
num_epoch: 16
num_workers: 10
optimizer:
  args:
    lr: <lr>
    momentum: 0.9
    nesterov: false
    params: null
    weight_decay: 0.0001
  obj: torch.optim.SGD
preprocessor:
  augmentations: <augmentations>
  feature_extractor: <feature_extractor>
  label_encoder: <label_encoder>
  wav_reader: <wav_reader>
reverb: /home/zjy/project/3D-Speaker/egs/3dspeaker/language-identification/data/rirs/wav.scp
sample_rate: 16000
save_epoch_freq: 2
speed_pertub: false
warmup_epoch: 1
wav_len: 3.0
wav_reader:
  args:
    duration: <wav_len>
    sample_rate: <sample_rate>
    speed_pertub: <speed_pertub>
  obj: speakerlab.process.processor_para.WavReader
````
